# Generated by Django 2.0 on 2018-03-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20171230_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdata',
            name='image_thumbnail_data',
        ),
        migrations.AlterField(
            model_name='processdata',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='image_data',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='user_id',
            field=models.BigIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='weekend_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
