# Generated by Django 3.1 on 2020-09-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20180301_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdata',
            name='process_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='project_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='processdata',
            name='task_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
