# Generated by Django 3.1 on 2020-09-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_processeddata_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='image_data',
            field=models.TextField(blank=True),
        ),
    ]
