# Generated by Django 3.1 on 2020-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20200902_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='image_data',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
