# Generated by Django 3.1 on 2020-09-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_auto_20200903_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='image_data',
            field=models.TextField(null=True),
        ),
    ]
