# Generated by Django 3.1 on 2020-09-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_auto_20200903_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='image_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
